#############################################################################
# Makefile for building: libsearchtonal.a
# Generated by qmake (3.0) (Qt 5.0.1) on: Mon Apr 22 10:25:46 2013
# Project:  project.pro
# Template: lib
# Command: /Users/slopes/Documents/Qt/Qt5.0.1/5.0.1/clang_64/bin/qmake -spec macx-xcode -o searchtonal.xcodeproj/project.pbxproj project.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/slopes/Documents/Qt/Qt5.0.1/5.0.1/clang_64/bin/qmake
searchtonal.xcodeproj/project.pbxproj: project.pro ../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-xcode/qmake.conf ../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/qdevice.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/device_config.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/unix.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base-macx.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/g++-base.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/g++-macx.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac-minimum-version.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/qconfig.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-xcode/qmake.conf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_post.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/default_pre.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_pre.prf \
		vclib_default.pri \
		lib_audioops.pri \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/release.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_post.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/static.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/staticlib.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/resources.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/moc.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/yacc.prf \
		../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/lex.prf \
		project.pro \
		/Users/slopes/Documents/Qt/Qt5.0.1/5.0.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/slopes/Documents/Qt/Qt5.0.1/5.0.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-xcode -o searchtonal.xcodeproj/project.pbxproj project.pro
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_pre.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/qdevice.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/device_config.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/shell-unix.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/unix.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base-macx.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/g++-base.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/g++-macx.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac-minimum-version.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/qconfig.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_functions.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_config.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-xcode/qmake.conf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_post.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_pre.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/default_pre.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_pre.prf:
vclib_default.pri:
lib_audioops.pri:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/release.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_post.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/static.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/staticlib.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/warn_on.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/resources.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/moc.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/thread.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/rez.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exceptions.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/yacc.prf:
../../../../../Qt/Qt5.0.1/5.0.1/clang_64/mkspecs/features/lex.prf:
project.pro:
/Users/slopes/Documents/Qt/Qt5.0.1/5.0.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/slopes/Documents/Qt/Qt5.0.1/5.0.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o searchtonal.xcodeproj/project.pbxproj project.pro

qmake_all: FORCE

